### ISSUE TITLE
Example of inpaint doesn't work for Stable Diffusion 2.1

### ISSUE THREAD

**Issue by Emulator000** [LaurentMazare/diffusers-rs#60]
I'm trying the same example for the 2.1 configuration, downloaded the appropriate CLIP, UNET and VAE and converted them correctly but it does not seems to work.

Command:
```sh
cargo run --example stable-diffusion-inpaint --features clap -- --sd-version="v2-1" --prompt "Face of a yellow cat, high resolution, sitting on a park bench." --input-image="temp/dog.png" --mask-image="temp/dog_mask.png" --width=512 --height=512
```

This is the output that i get with the dog/cat example that works perfectly with Stable Diffusion 1.5:
![image](https://user-images.githubusercontent.com/15048541/235883311-7831da5b-8619-4388-8634-78e6bdd2a4a9.png)

It seems that the inpainted area doensn't correctly populate.

Any possible reason for that? Should the example/code be adapted for some additional steps for the 2.1 version?

**Comment by LaurentMazare** [comment]
Ah it seems that actually one difference was that the scheduler for stable-diffusion 2.1 uses a prediction type of `v_prediction` in normal generation but uses a prediction type of `epsilon` for inpainting (whereas stable-diffusion 1.5 uses `epsilon` for both). I've just merged a PR #63 that should hopefully help with this - at least on a single generated image it looks better now.
![sd_final](https://github.com/LaurentMazare/diffusers-rs/assets/1041292/8fd25d2c-3f98-45e7-982d-64ea2b23bff0)

There is still a scheduler inconsistency as we use DDIM rather than PNDM - also using a proper DPM solver would likely help here but hopefully this doesn't make much of a difference.
Please give a spin to the current github tip if you can and let us know how it gets.
