### ISSUE TITLE
Integration with Stable Diffusion XL 1.0 ?

### ISSUE THREAD

**Issue by Cyril-Cf** [LaurentMazare/diffusers-rs#78]
Hello,

That might be a silly question, but will there be future integrations with SDXL in a near future? It seems to me that the XL version is pretty different so I figured we couldn't use it as is. 

Thanks for your help!

**Comment by LaurentMazare** [comment]
Actually if you exclude the refiner net, sdxl is pretty close to earlier versions of stable diffusion - the only difference being on the tokenization side (using two tokenizers rather than one). You can see here the [pull request](https://github.com/huggingface/candle/pull/647/files) that added it to candle.
I don't think it would be that much effort to support, though I would recommend giving a spin to the [candle version](https://github.com/huggingface/candle/tree/main/candle-examples/examples/stable-diffusion), and note that candle also supports [wuerstchen](https://github.com/huggingface/candle/tree/main/candle-examples/examples/wuerstchen) for image generation.
